# -*- coding: utf-8 ; mode: org -*-

#+TITLE:  Third report
#+DATE:   2013-12-04
#+AUTHOR: Michele Orru`
#+EMAIL:  maker@tumbolandia.net
#+TODO:   DOING DONE TODO


This third week has been spent finalizing Wiener's Attack on small private
exponent, and starting Dixon's, Pollard's (p-1) factorization.
It would be nice to receive feddback on the implmented parts.

* DONE Finalize and test Wiener's attack.
  1) Complete the implementation of a square root algorithm for integers
  2) Complete Wiener's attack
  3) Unittest, and test over a fake certificate
* DOING Starting Dixon's attack for factorizing the public modulus
  Just spent some time looking at the mathematical basis behing the attack,
  started thinking about the algorithm.
  Sources are now, the course lecture (lecture 3), and this [[http://cse.iitkgp.ac.in/~debdeep/courses_iitkgp/Crypto/slides/Factorization.pdf][slides]] found on the
  internetz.

  Note: On the slides, at page 10 I see that -1 ∈ B, the factor basis. Though, on
  lecture 3, I read "A set B finite and non-empty of prime positive
  integers". What is true, what is wrong?
* DOING Starting Pollard's (p-1) attack for factorizing the public modulus
  I am currently doing some research here, sorting out the best choiceof
  B. Though, it seems that [[https://en.wikipedia.org/wiki/Pollard's_p_%E2%88%92_1_algorithm#How_to_choose_B.3F][wikipedia]] 's section is wrong.
* DOING Starting book/
  Following Emanuele's suggestion, I've created the book/ directory contains the
  thesis book, and right now I'm just taking note of some algs I've been using;
  so, nothing ready, but might be useful in the future.
